<?php
require_once '../functions.php';requireAdmin();$pageTitle='Categories';
$action=$_GET['action']??'';$id=(int)($_GET['id']??0);
if($action==='delete'&&$id){try{$s=$pdo->prepare("DELETE FROM categories WHERE id=?");$s->execute([$id]);$_SESSION['flash']=['type'=>'success','message'=>'Category deleted.'];}catch(Exception $e){$_SESSION['flash']=['type'=>'danger','message'=>'Cannot delete a category that has products.'];}redirect('categories.php');}
if($_SERVER['REQUEST_METHOD']==='POST'){$name=trim($_POST['name']);$desc=trim($_POST['description']);$image=trim($_POST['image']);if($_POST['id']){$s=$pdo->prepare("UPDATE categories SET name=?,image=?,description=? WHERE id=?");$s->execute([$name,$image,$desc,(int)$_POST['id']]);}else{$s=$pdo->prepare("INSERT INTO categories(name,image,description) VALUES(?,?,?)");$s->execute([$name,$image,$desc]);}$_SESSION['flash']=['type'=>'success','message'=>'Category saved.'];redirect('categories.php');}
$edit=null;if($action==='edit'&&$id){$s=$pdo->prepare("SELECT * FROM categories WHERE id=?");$s->execute([$id]);$edit=$s->fetch();}
$rows=$pdo->query("SELECT * FROM categories ORDER BY id DESC")->fetchAll();require 'header.php';
?>
<h1>Categories</h1>
<?php if($action==='add'||$edit):?><div class="form-card mb-4"><h4><?= $edit?'Edit':'Add' ?> Category</h4><form method="post" class="row g-3"><input type="hidden" name="id" value="<?=$edit['id']??0?>"><div class="col-md-6"><label class="form-label">Category Name</label><input class="form-control" name="name" value="<?=e($edit['name']??'')?>" required></div><div class="col-md-6"><label class="form-label">Category Image Path</label><input class="form-control" name="image" value="<?=e($edit['image']??'assets/images/category-fiction.svg')?>" required></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description"><?=e($edit['description']??'')?></textarea></div><div><button class="btn btn-dark">Save Category</button> <a href="categories.php" class="btn btn-outline-dark">Cancel</a></div></form></div><?php else:?><a href="?action=add" class="btn btn-dark mb-3">+ Add Category</a><?php endif;?>
<div class="table-responsive"><table class="table bg-white"><thead><tr><th>ID</th><th>Image</th><th>Name</th><th>Description</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=$r['id']?></td><td><img class="admin-thumb" src="../<?=e($r['image'])?>"></td><td><?=e($r['name'])?></td><td><?=e($r['description'])?></td><td><a class="btn btn-sm btn-outline-dark" href="?action=edit&id=<?=$r['id']?>">Edit</a> <a class="btn btn-sm btn-outline-danger" href="?action=delete&id=<?=$r['id']?>" onclick="return confirm('Delete category?')">Delete</a></td></tr><?php endforeach;?></tbody></table></div>
<?php require 'footer.php';?>
