<?php
require_once '../functions.php';requireAdmin();$pageTitle='Products';$action=$_GET['action']??'';$id=(int)($_GET['id']??0);
if($action==='delete'&&$id){try{$s=$pdo->prepare("DELETE FROM products WHERE id=?");$s->execute([$id]);$_SESSION['flash']=['type'=>'success','message'=>'Product deleted.'];}catch(Exception $e){$_SESSION['flash']=['type'=>'danger','message'=>'Product cannot be deleted because it is used in an order.'];}redirect('products.php');}
if($_SERVER['REQUEST_METHOD']==='POST'){$data=[(int)$_POST['category_id'],trim($_POST['name']),trim($_POST['image']),floatval($_POST['price']),floatval($_POST['discount']),trim($_POST['description']),trim($_POST['specifications']),(int)$_POST['stock_quantity'],(int)$_POST['status']];if((int)$_POST['id']){$data[]=(int)$_POST['id'];$s=$pdo->prepare("UPDATE products SET category_id=?,name=?,image=?,price=?,discount=?,description=?,specifications=?,stock_quantity=?,status=? WHERE id=?");$s->execute($data);}else{$s=$pdo->prepare("INSERT INTO products(category_id,name,image,price,discount,description,specifications,stock_quantity,status) VALUES(?,?,?,?,?,?,?,?,?)");$s->execute($data);}$_SESSION['flash']=['type'=>'success','message'=>'Product saved.'];redirect('products.php');}
$edit=null;if($action==='edit'&&$id){$s=$pdo->prepare("SELECT * FROM products WHERE id=?");$s->execute([$id]);$edit=$s->fetch();}
$cats=$pdo->query("SELECT id,name FROM categories WHERE status=1 ORDER BY name")->fetchAll();$rows=$pdo->query("SELECT p.*,c.name category_name FROM products p JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC")->fetchAll();require 'header.php';
?>
<h1>Products</h1>
<?php if($action==='add'||$edit):?><div class="form-card mb-4"><h4><?= $edit?'Edit':'Add' ?> Product</h4><form method="post" class="row g-3"><input type="hidden" name="id" value="<?=$edit['id']??0?>">
<div class="col-md-6"><label class="form-label">Category</label><select class="form-select" name="category_id" required><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=($edit['category_id']??'')==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></div>
<div class="col-md-6"><label class="form-label">Product Name</label><input class="form-control" name="name" value="<?=e($edit['name']??'')?>" required></div>
<div class="col-md-6"><label class="form-label">Image Path</label><input class="form-control" name="image" value="<?=e($edit['image']??'assets/images/book-1.svg')?>" required></div>
<div class="col-md-2"><label class="form-label">Price</label><input class="form-control" type="number" step="0.01" name="price" value="<?=e($edit['price']??0)?>" required></div>
<div class="col-md-2"><label class="form-label">Discount</label><input class="form-control" type="number" step="0.01" name="discount" value="<?=e($edit['discount']??0)?>"></div>
<div class="col-md-2"><label class="form-label">Stock</label><input class="form-control" type="number" name="stock_quantity" value="<?=e($edit['stock_quantity']??0)?>" required></div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description"><?=e($edit['description']??'')?></textarea></div>
<div class="col-12"><label class="form-label">Specifications</label><textarea class="form-control" name="specifications"><?=e($edit['specifications']??'')?></textarea></div>
<div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="1" <?=($edit['status']??1)?'selected':''?>>Active</option><option value="0" <?=isset($edit['status'])&&!$edit['status']?'selected':''?>>Inactive</option></select></div>
<div><button class="btn btn-dark">Save Product</button> <a href="products.php" class="btn btn-outline-dark">Cancel</a></div></form></div><?php else:?><a href="?action=add" class="btn btn-dark mb-3">+ Add Product</a><?php endif;?>
<div class="table-responsive"><table class="table bg-white align-middle"><thead><tr><th>ID</th><th>Image</th><th>Name</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=$r['id']?></td><td><img class="admin-thumb" src="../<?=e($r['image'])?>"></td><td><?=e($r['name'])?></td><td><?=e($r['category_name'])?></td><td>₹<?=number_format(productPrice($r),2)?></td><td><?=$r['stock_quantity']?></td><td><?=$r['status']?'Active':'Inactive'?></td><td><a class="btn btn-sm btn-outline-dark" href="?action=edit&id=<?=$r['id']?>">Edit</a> <a class="btn btn-sm btn-outline-danger" href="?action=delete&id=<?=$r['id']?>" onclick="return confirm('Delete product?')">Delete</a></td></tr><?php endforeach;?></tbody></table></div>
<?php require 'footer.php';?>
